### PR TITLE
don't break/replace old c-d lib

### PR DESCRIPTION
**Pull request by monsta**

### CODE REVIEW

**Comment by GLolol** [comment]
Why? The package name is supposed to match the library version.

**Comment by monsta** [comment]
@JosephMcc can tell you how it caused installation problems on his machine.

Besides, the lib API version already was 4 - which didn't match the name.

**Comment by GLolol** [comment]
@JosephMcc was the one who committed 01d5fec, which is reverted here.

**Comment by monsta** [comment]
I know, and that was a hack, and I already asked him if this PR solves the issue.

**Comment by GLolol** [comment]
Oh, I see.

**Pull request merged**
