### PR TITLE
Improve debian packaging

### PR DESCRIPTION
**Pull request by Fantu**

### CODE REVIEW

**Comment by clefebvre** [comment]
Can you explain https://github.com/linuxmint/cinnamon-desktop/pull/96/commits/651175e336292f51a1e3943a58edf6e6c9575ab4?

Other than that, everything looks good.

Do we really need to include a list of symbols in the git tree? That content will be obsolete with every new build.. and it looks like it could very well be generated automatically.

**Comment by Fantu** [comment]
if is not mainteined good probably is better avoid it, if you want remove 651175e commit.
the content need to be updated only if some api will be added/modified/changed and can be useful to understand if the abi need to be dumped

**Comment by Fantu** [comment]
probably I'll rebase this in few days and I'll other improvements from debian
@clefebvre about migration to meson can be good use debhelper from stretch-backports instead some manually addition? (ubuntu 18.04 already have debhelper updated with meson support)
I'll try to split all changes in different commits with good descriptions

**Comment by Fantu** [comment]
@clefebvre rebased and add some other improvements and small fixes, if you don't want commit "Bump version to 3.7.0 for testing" remove it
also tested build http://debomatic-amd64.debian.net/distribution#stretch/cinnamon-desktop/3.7.0~1/buildlog
other important improvements are needed but I suppose is not possible now, for example I not understand if you still want support s.o. older that stretch and bionic
some other possible improvement not done for now:
- meson support without manual addition for basic build support using meson require debhelper>=10.3 newer from backport should be also better; migrating dh compat from 9 to 11 make possible also other small improvements and for what I saw few days ago also helped to found a partial build error where on dh 9 of same packages before continued anyway
- as spotted also by lintian: debian-control-has-obsolete-dbg-package (same of all other packages), tell me if will be possible switch to -dbgsym

**Comment by Fantu** [comment]
now that I had confirm of mint18 support dropped I added other improvements, I also tested build on stretch:
http://debomatic-amd64.debian.net/distribution#stretch/cinnamon-desktop/3.7.0~2

**Comment by clefebvre** [comment]
All merged except for version bump.

**Pull request closed without merging**
