### PR TITLE
Add Codespell workflow and fix some typo

### PR DESCRIPTION
**Pull request by Fantu**

### CODE REVIEW

**Comment by mtwebster** [comment]
Would this workflow be better off as part of our auto-builds (see https://github.com/linuxmint/github-actions), rather than adding it to every repo? They get triggered for PRs as well.

It wouldn't be on ubuntu-latest container, but I still think it would do the job off mint/lmde images.

**Comment by Fantu** [comment]
If will not be a problem to manage exclusions of any repository in it can be better.
Small note: it works only for PR this action.
If you want to do it you can start with the action from here but add also the esclusion from https://github.com/linuxmint/cinnamon-settings-daemon/pull/385/commits/9749faa9e7b2c652142d3af26bf688bece9d4362 so will be:
```
skip: ChangeLog,*.po,LINGUAS
# word to exclude must be always lowercase as must be same of the codespell dictionary
ignore_words_list: gir,tyes
```
and from my PR cherry-pick the other commit with the fixes done
after on new PR of other components will appear many spell error detected and also other possible things to exclude anyway with `only_warn: 1` don't fail the tests so don't force contributors to resolve errors already present but at least warns inline in the changed code and under the first errors in the one not changed by the PR

**Comment by mtwebster** [comment]
Ok, I added codespell to our CI:
https://github.com/linuxmint/github-actions/commit/cb715827ba6090a605072b159257e42f30bde9d0

Tested on this repo:
https://github.com/linuxmint/cinnamon-desktop/actions/runs/7877089417

I fixed the file in cinnamon-settings-daemon so we don't need to exclude 'tyes'. Let me know if anything doesn't look right. If exceptions ever become an issue we can still specify them per-repo (Add another input [here](https://github.com/linuxmint/cinnamon-desktop/blob/master/.github/workflows/build.yml#L18-L25), like `dependencies`).

Want to update these prs with just the spelling corrections?  Thanks

**Comment by Fantu** [comment]
Inserting it into the build job currently runs it 3 times, it would be better to find a way to run it only once, then I think it would be fine to keep it "global".
I updated my 2 PR keeping only typo fixes.
Looking c-s-d codespell needs to add `,*.svg` (can be useful also in others repo) and `,requestor` to ignore_words_list

**Comment by mtwebster** [comment]
Ok I made a few more changes:
https://github.com/linuxmint/github-actions/commit/8fb9c7c4a7f4670e8c3f8d0637e269978e2552c3

- It only runs on one machine now
- You can specify per-repo words/files to skip, in addition to the 'defaults' (Changelog, .po, etc...)

This way someone opening a PR can add to the repo ignore lists instead of us having to update our github-actions every time.

**Pull request merged**
