### PR TITLE
replace the rubbish pnp.ids file

### PR DESCRIPTION
**Pull request by leigh123linux**
The file never looked like that before from gnome.

https://git.gnome.org/browse/gnome-desktop/commit/libgnome-desktop/pnp.ids?h=gnome-3-10&id=dcb4bc7693cc00c5374393035545a21bcb9e8012

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi leigh, we need more than that to change it.

Can you find out if that fixes/breaks anything? Does it detect your screen vendor info better with that change for instance?

**Comment by leigh123linux** [comment]
To be honest it doesn't make any difference to my desktop PC, it shows 'Iiyama North America' with or without it.
My Lenovo shows 'laptop'  with or without it.

**Comment by clefebvre** [comment]
Ah well then :)

**Comment by leigh123linux** [comment]
so your going to keep the meaningless on with all the fedora and redhat git refences :sunglasses:

**Comment by clefebvre** [comment]
Yes.

**Pull request closed without merging**
